name: Test-Caller

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch
on:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

env:
  REPO_OWNER: GSDragoon
  REPO_NAME: repository-dispatch-test

jobs:
  test-caller:
    runs-on: ubuntu-latest
    steps:

      # https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
      - name: 'Execute Remote Workflow'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_PAT }}" \
            https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/dispatches \
            -d '{"event_type":"test-type-1","client_payload":{"value1":false,"value2":"foobar"}}' \
            --no-progress-meter --show-error --fail-with-body
